parameters:
    forum_service.class: Inkstand\Activity\ForumBundle\Service\ForumService

services:
    forum_service:
        class:     "%forum_service.class%"
        arguments: [@doctrine.orm.entity_manager]
