Inkstand\ResourceLibraryBundle\Entity\ResourceTagEntry:
    type: entity
    table: lms_resource_tag_entry
    id:
        tagEntryId:
            type: integer
            id: true
            generator:
                strategy: AUTO
            column: tag_entry_id
    fields:
        objectId:
            type: integer
            column: object_id
        tagId:
            type: integer
            column: tag_id
        value:
            type: text
    manyToOne:
        object:
            targetEntity: Resource
            inversedBy: tagEntries
            joinColumn:
                name: object_id
                referencedColumnName: resource_id
                nullable: false
        tag:
            targetEntity: ResourceTag
            inversedBy: tagEntries
            joinColumn:
                name: tag_id
                referencedColumnName: tag_id
                nullable: false
    lifecycleCallbacks: {  }
