Inkstand\ResourceLibraryBundle\Entity\ResourceTag:
    type: entity
    table: lms_resource_tag
    id:
        tagId:
            type: integer
            column: tag_id
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        type:
            type: string
            length: 255
        defaultValue:
            type: text
            column: default_value
            nullable: true
        choices:
            type: text
            nullable: true
        uniqueName:
            type: string
            length: 255
            column: unique_name
        required:
            type: boolean
    oneToMany:
        tagEntries:
            targetEntity: ResourceTagEntry
            mappedBy: tag
    lifecycleCallbacks: {  }
