Inkstand\ResourceLibraryBundle\Entity\Resource:
    type: entity
    table: lms_resource
    repositoryClass: Inkstand\ResourceLibraryBundle\Entity\ResourceRepository
    id:
        resourceId:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            column: resource_id
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: false
            precision: 0
        resourceFileReferenceId:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: resource_file_reference_id
        thumbnailFileReferenceId:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: thumbnail_file_reference_id
        description:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
        topicId:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: topic_id
        ratingId:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: rating_id
    manyToMany:
        topics:
            targetEntity: Inkstand\ResourceLibraryBundle\Entity\Topic
            joinTable:
                name: lms_resource_topics
                joinColumns:
                    resource_id:
                        referencedColumnName: resource_id
                inverseJoinColumns:
                    topic_id:
                        referencedColumnName: topic_id
    manyToOne:
        resourceFileReference:
            targetEntity: Inkstand\Bundle\CoreBundle\Entity\FileReference
            cascade:
                - persist
            mappedBy: null
            inversedBy: null
            joinColumns:
                resource_file_reference_id:
                    referencedColumnName: file_reference_id
            orphanRemoval: false
        thumbnailFileReference:
            targetEntity: Inkstand\Bundle\CoreBundle\Entity\FileReference
            cascade:
                - persist
            mappedBy: null
            inversedBy: null
            joinColumns:
                thumbnail_file_reference_id:
                    referencedColumnName: file_reference_id
            orphanRemoval: false
    oneToOne:
        rating:
            targetEntity: Inkstand\Library\RatingBundle\Entity\Rating
            cascade:
                - remove
                - persist
            mappedBy: null
            inversedBy: null
            joinColumns:
                rating_id:
                    referencedColumnName: rating_id
            orphanRemoval: false
    oneToMany:
        tagEntries:
            targetEntity: ResourceTagEntry
            mappedBy: object
            cascade: ["persist", "remove"]
    lifecycleCallbacks: {  }
