Inkstand\ResourceLibraryBundle\Entity\ResourceTag:
    type: entity
    table: lms_resource_tag
    id:
        tagId:
            type: integer
            id: true
            generator:
                strategy: AUTO
            column: tag_id
    fields:
        name:
            type: string
            length: 255
        type:
            type: string
            length: 255
        defaultValue:
            type: text
            nullabe: true
            column: default_value
        choices:
            type: text
            nullable: true
        code:
            type: string
            length: 255
            column: code
        required:
            type: boolean
    oneToMany:
        tagEntries:
            targetEntity: ResourceTagEntry
            mappedBy: tag
            cascade: ["persist", "remove"]
    lifecycleCallbacks: {  }
