Inkstand\ResourceLibraryBundle\Entity\Topic:
    type: entity
    table: lms_resource_topic
    id:
        topicId:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            column: topic_id
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: false
            precision: 0
        description:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
    lifecycleCallbacks: {  }
