parameters:
    widget_service.class:        Inkstand\Bundle\CoreBundle\Service\WidgetService
    page_template_service.class: Inkstand\Bundle\CoreBundle\Service\PageTemplateService
    plugin_service.class:        Inkstand\Bundle\CoreBundle\Service\PluginService

services:
    widget_service:
        class: "%widget_service.class%"
        arguments: [@event_dispatcher]

    page_template_service:
        class: "%page_template_service.class%"
        arguments: [@doctrine.orm.entity_manager, @widget_service]

    plugin_service:
        class: "%plugin_service.class%"
        arguments: [@doctrine.orm.entity_manager]

    menu_builder:
        class: Inkstand\Bundle\CoreBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory"]

    main_menu:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: menu_builder
        factory_method: createMainMenu
        arguments: ["@request_stack"]
        tags:
            - { name: knp_menu.menu, alias: main } # The alias is what is used to retrieve the menu

    core_widget_listener:
            class: Inkstand\Bundle\CoreBundle\EventListener\WidgetListener
            tags:
                - { name: kernel.event_listener, event: inkstand.core.widget_register, method: onWidgetRegister }