parameters:
    widget_service.class:                        Inkstand\Bundle\CoreBundle\Service\WidgetService
    page_template_service.class:                 Inkstand\Bundle\CoreBundle\Service\PageTemplateService
    plugin_service.class:                        Inkstand\Bundle\CoreBundle\Service\PluginService
    inkstand_core.context.class:                 Inkstand\Bundle\CoreBundle\Service\ContextService
    inkstand_core.context_role_assignment.class: Inkstand\Bundle\CoreBundle\Service\ContextRoleAssignmentService
    inkstand_core.voter.class:                   Inkstand\Bundle\CoreBundle\Service\VoterService
    inkstand_core.voter_action.class:            Inkstand\Bundle\CoreBundle\Service\VoterActionService
    inkstand_core.voter_action_role_assignment.class: Inkstand\Bundle\CoreBundle\Service\VoterActionRoleAssignmentService
    inkstand_core.role.class:                    Inkstand\Bundle\CoreBundle\Service\RoleService

    # Scripts parameters
    inkstand_core.scripts.role.class:            Inkstand\Bundle\CoreBundle\Scripts\RoleScripts

services:
    widget_service:
        class: "%widget_service.class%"
        arguments: [@event_dispatcher]

    page_template_service:
        class: "%page_template_service.class%"
        arguments: [@doctrine.orm.entity_manager, @widget_service]

    plugin_service:
        class: "%plugin_service.class%"
        arguments: [@doctrine.orm.entity_manager]

    inkstand_core.context:
        class: "%inkstand_core.context.class%"
        arguments: [@doctrine.orm.entity_manager, @inkstand_core.context_role_assignment, @security.token_storage]

    inkstand_core.context_role_assignment:
        class: "%inkstand_core.context_role_assignment.class%"
        arguments: [@doctrine.orm.entity_manager]

    inkstand_core.role:
        class: "%inkstand_core.role.class%"
        arguments: [@doctrine.orm.entity_manager]

    inkstand_core.voter:
        class: "%inkstand_core.voter.class%"
        arguments: [@doctrine.orm.entity_manager, @inkstand_core.role, @inkstand_core.voter_action, @inkstand_core.voter_action_role_assignment,, @service_container]

    inkstand_core.voter_action:
        class: "%inkstand_core.voter_action.class%"
        arguments: [@doctrine.orm.entity_manager]

    inkstand_core.voter_action_role_assignment:
        class: "%inkstand_core.voter_action_role_assignment.class%"
        arguments: [@doctrine.orm.entity_manager]

    # Scripts
    inkstand_core.scripts.role:
        class: "%inkstand_core.scripts.role.class%"
        arguments: [@service_container]

    menu_builder:
        class: Inkstand\Bundle\CoreBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory"]

    main_menu:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: menu_builder
        factory_method: createMainMenu
        arguments: ["@request_stack"]
        tags:
            - { name: knp_menu.menu, alias: main } # The alias is what is used to retrieve the menu

    core_widget_listener:
            class: Inkstand\Bundle\CoreBundle\EventListener\WidgetListener
            tags:
                - { name: kernel.event_listener, event: inkstand.core.widget_register, method: onWidgetRegister }