inkstand_calendar:
    resource: "@InkstandCalendarBundle/Resources/config/routing.yml"
    prefix:   /

inkstand_tag:
    resource: "@InkstandTagBundle/Resources/config/routing.yml"
    prefix:   /

inkstand_rating:
    resource: "@InkstandRatingBundle/Resources/config/routing.yml"
    prefix:   /

inkstand_resource_library:
    resource: "@InkstandResourceLibraryBundle/Resources/config/routing.yml"
    prefix:   /

inkstand_enrollment:
    resource: "@InkstandEnrollmentBundle/Resources/config/routing.yml"
    prefix:   /

inkstand_lrs:
    resource: "@InkstandLrsBundle/Resources/config/routing.yml"
    prefix:   /

inkstand_scorm:
    resource: "@InkstandScormBundle/Resources/config/routing.yml"
    prefix:   /

inkstand_core:
    resource: "@InkstandCoreBundle/Resources/config/routing.yml"
    prefix:   /

inkstand_forum:
    resource: "@InkstandForumBundle/Resources/config/routing.yml"
    prefix:   /

inkstand_external_link:
    resource: "@InkstandExternalLinkBundle/Resources/config/routing.yml"
    prefix:   /

inkstand_user:
    resource: "@InkstandUserBundle/Resources/config/routing.yml"
    prefix:   /

inkstand_theme:
    resource: "@InkstandThemeBundle/Resources/config/routing.yml"
    prefix:   /

inkstand_course:
    resource: "@InkstandCourseBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix:   /
