<?php

namespace Inkstand\Bundle\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PageTemplateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageTemplateRepository extends EntityRepository
{
}
