Inkstand\Library\TagBundle\Entity\Tag:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: uniqueName
    properties:
        name:
            - NotBlank: ~
        uniqueName:
            - NotBlank: ~
        type:
            - NotBlank: ~
        category:
            - NotBlank: ~