parameters:
    course_category_service.class:        Inkstand\Bundle\CourseBundle\Service\CourseCategoryService
    course_service.class:                 Inkstand\Bundle\CourseBundle\Service\CourseService
    activity_service.class:               Inkstand\Bundle\CourseBundle\Service\ActivityService
    inkstand_course.activity_type.class:  Inkstand\Bundle\CourseBundle\Service\ActivityTypeService
    module_service.class:                 Inkstand\Bundle\CourseBundle\Service\ModuleService
    enrollment_service.class:             Inkstand\Bundle\CourseBundle\Service\EnrollmentService
    inkstand_course.enrollment_type.class: Inkstand\Bundle\CourseBundle\Service\EnrollmentTypeService
    enrollment.manual.service.class:      Inkstand\Bundle\CourseBundle\Service\ManualEnrollmentService
    course_enrollment_type_service.class: Inkstand\Bundle\CourseBundle\Service\CourseEnrollmentTypeService
    inkstand_course.voter.course_voter.class: Inkstand\Bundle\CourseBundle\Voter\CourseVoter

services:
    # Entity services
    course_category_service:
        class:     "%course_category_service.class%"
        arguments: [@doctrine.orm.entity_manager]
    course_service:
        class:     "%course_service.class%"
        arguments: [@doctrine.orm.entity_manager]
    activity_service:
        class:     "%activity_service.class%"
        arguments: [@doctrine.orm.entity_manager]
    inkstand_course.activity_type:
        class:     "%inkstand_course.activity_type.class%"
        arguments: [@doctrine.orm.entity_manager]
    module_service:
        class:     "%module_service.class%"
        arguments: [@doctrine.orm.entity_manager]
    enrollment_service:
        class:     "%enrollment_service.class%"
        arguments: [@doctrine.orm.entity_manager, @event_dispatcher, @service_container]

    inkstand_course.enrollment_type:
        class:     "%inkstand_course.enrollment_type.class%"
        arguments: [@doctrine.orm.entity_manager, @service_container]

    enrollment.manual.service:
        class:     "%enrollment.manual.service.class%"
        arguments: [@enrollment_service]
    course_enrollment_type_service:
        class:     "%course_enrollment_type_service.class%"
        arguments: [@doctrine.orm.entity_manager]


    # Form types
    inkstand_course.form.type.task:
        class: Inkstand\Bundle\CourseBundle\Form\Type\CourseType
        arguments: [@course_category_service]
        tags:
            - { name: form.type, alias: course }

    inkstand_course.form.type.course_category:
            class: Inkstand\Bundle\CourseBundle\Form\Type\CourseCategoryType
            arguments: [@course_category_service]
            tags:
                - { name: form.type, alias: courseCategory }

    inkstand_course.enrollment.manual_enrollment:
        class: Inkstand\Bundle\CourseBundle\Enrollment\ManualEnrollment

    course_widget_listener:
        class: Inkstand\Bundle\CourseBundle\EventListener\WidgetListener
        tags:
            - { name: kernel.event_listener, event: inkstand.core.widget_register, method: onWidgetRegister }

    # Voters
    inkstand_course.voter.course_voter:
        class:      "%inkstand_course.voter.course_voter.class%"
        arguments:  [@inkstand_core.role]
        public:     true
        tags:
            - { name: security.voter }