parameters:
    course_category_service.class: Inkstand\Bundle\CourseBundle\Service\CourseCategoryService
    course_service.class:          Inkstand\Bundle\CourseBundle\Service\CourseService

    course_controller.class:       Inkstand\Bundle\CourseBundle\Controller\CourseController

services:
    # Entity services
    course_category_service:
        class:     "%course_category_service.class%"
        arguments: [@doctrine.orm.entity_manager]
    course_service:
        class:     "%course_service.class%"
        arguments: [@doctrine.orm.entity_manager]

    # Form types
    inkstand_course.form.type.task:
        class: Inkstand\Bundle\CourseBundle\Form\Type\CourseType
        arguments: [@course_category_service]
        tags:
            - { name: form.type, alias: course }