parameters:
    course_category_service.class: Inkstand\Bundle\CourseBundle\Service\CourseCategoryService
    course_service.class:          Inkstand\Bundle\CourseBundle\Service\CourseService
    activity_service.class:        Inkstand\Bundle\CourseBundle\Service\ActivityService
    activity_type_service.class:   Inkstand\Bundle\CourseBundle\Service\ActivityTypeService
    module_service.class:          Inkstand\Bundle\CourseBundle\Service\ModuleService

services:
    # Entity services
    course_category_service:
        class:     "%course_category_service.class%"
        arguments: [@doctrine.orm.entity_manager]
    course_service:
        class:     "%course_service.class%"
        arguments: [@doctrine.orm.entity_manager]
    activity_service:
        class:     "%activity_service.class%"
        arguments: [@doctrine.orm.entity_manager]
    activity_type_service:
        class:     "%activity_type_service.class%"
        arguments: [@doctrine.orm.entity_manager]
    module_service:
        class:     "%module_service.class%"
        arguments: [@doctrine.orm.entity_manager]

    # Form types
    inkstand_course.form.type.task:
        class: Inkstand\Bundle\CourseBundle\Form\Type\CourseType
        arguments: [@course_category_service]
        tags:
            - { name: form.type, alias: course }