parameters:
    inkstand_enrollment.enrollment_type.access_code.class: Inkstand\EnrollmentBundle\EnrollmentType\AccessCodeEnrollmentType

services:
    inkstand_enrollment.enrollment_type.access_code:
        class:     "%inkstand_enrollment.enrollment_type.access_code.class%"
        arguments: [@enrollment_service, @doctrine.orm.entity_manager]
        public:    true
        tags:
            - { name: inkstand.enrollment_type }
