parameters:
    inkstand_scorm.scorm.class: Inkstand\Activity\ScormBundle\Service\ScormService

services:
    inkstand_scorm.scorm:
        class: "%inkstand_scorm.scorm.class%"
        arguments: [@inkstand_core.filesystem, "%kernel.cache_dir%"]