parameters:
    inkstand_resource_library.resource.class: Inkstand\ResourceLibraryBundle\Service\ResourceService
    inkstand_resource_library.voter.resource_voter.class: Inkstand\ResourceLibraryBundle\Voter\ResourceVoter
    inkstand_resource_library.voter.topic_voter.class: Inkstand\ResourceLibraryBundle\Voter\TopicVoter

    inkstand_resource_library.resource_tag_manager: Inkstand\ResourceLibraryBundle\Doctrine\ResourceTagManager
    inkstand_resource_library.model.tag.class: Inkstand\ResourceLibraryBundle\Entity\ResourceTag

services:
    inkstand_resource_library.resource:
        class: "%inkstand_resource_library.resource.class%"
        arguments: [@doctrine.orm.entity_manager]

    inkstand_resource_library.resource_tag_manager:
        class: "%inkstand_resource_library.resource_tag_manager%"
        arguments: [@form.factory, @doctrine.orm.entity_manager, "%inkstand_resource_library.model.tag.class%"]

    inkstand_resource_library.topic:
        class: Inkstand\ResourceLibraryBundle\Service\TopicService
        arguments: [@doctrine.orm.entity_manager]

    # Voters

    inkstand_resource_library.voter.resource_voter:
        class:      "%inkstand_resource_library.voter.resource_voter.class%"
        arguments:  [@inkstand_core.role]
        public:     true
        tags:
            - { name: security.voter }
            - { name: inkstand.voter }

    inkstand_resource_library.voter.topic_voter:
        class:      "%inkstand_resource_library.voter.topic_voter.class%"
        arguments:  [@inkstand_core.role]
        public:     true
        tags:
            - { name: security.voter }
            - { name: inkstand.voter }

    # Menus
    inkstand_resource_library.menu_builder:
        class: Inkstand\ResourceLibraryBundle\Menu\MenuBuilder
        arguments: [@knp_menu.factory]
        tags:
            - { name: knp_menu.menu_builder, method: createResourceRateBreadcrumbs, alias: resource_rate_breadcrumbs }