inkstand_lrs_homepage:
    path:     /hello/{name}
    defaults: { _controller: InkstandLrsBundle:Default:index }

inkstand_lrs_xapi_activty:
    resource: "@InkstandLrsBundle/Controller/XapiActivityController.php"
    type:     annotation
    prefix:   /xAPI

inkstand_lrs_xapi_statement:
    resource: "@InkstandLrsBundle/Controller/XapiStatementController.php"
    type:     annotation
    prefix:   /xAPI