parameters:
     inkstand_lrs.activity.class:  Inkstand\LrsBundle\Service\ActivityService
     inkstand_lrs.statement.class: Inkstand\LrsBundle\Service\StatementService

services:
     inkstand_lrs.activity:
         class: "%inkstand_lrs.activity.class%"
         arguments: [@doctrine.orm.entity_manager]

     inkstand_lrs.statement:
         class: "%inkstand_lrs.statement.class%"
         arguments: [@doctrine.orm.entity_manager]
