inkstand_user:
    resource: "@InkstandUserBundle/Controller/UserController.php"
    type:     annotation

inkstand_upload:
    resource: "@InkstandUserBundle/Controller/UploadController.php"
    type:     annotation