parameters:
    user_service.class: Inkstand\Bundle\UserBundle\Service\UserService

services:
    user_service:
        class: "%user_service.class%"
        arguments: [@doctrine.orm.entity_manager, @validator]
